---
- name: Install fonts
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - noto-fonts
    - ttf-bitstream-vera
    - ttf-dejavu
    - ttf-droid
    - ttf-freefont
    - ttf-hack
    - ttf-inconsolata
    - ttf-liberation
    - ttf-ubuntu-font-family
