---
- name: Install fonts
  pacman:
    name:
      - gnu-free-fonts
      - libertinus-font
      - noto-fonts
      - noto-fonts-emoji
      - powerline-fonts
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-droid
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-fira-sans
      - ttf-firacode-nerd
      - ttf-hack
      - ttf-inconsolata
      - ttf-liberation
      - ttf-roboto
      - ttf-ubuntu-font-family
    state: present
