---
- name: Install fonts
  pacman:
    name:
      - noto-fonts
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-droid
      - ttf-freefont
      - ttf-hack
      - ttf-inconsolata
      - ttf-liberation
      - ttf-roboto
      - ttf-ubuntu-font-family
    state: present
