---
- name: Install fonts
  pacman:
    name:
      - gnu-free-fonts
      - noto-fonts
      - noto-fonts-emoji
      - ttf-bitstream-vera
      - ttf-dejavu
      - ttf-droid
      - ttf-hack
      - ttf-inconsolata
      - ttf-liberation
      - ttf-roboto
      - ttf-ubuntu-font-family
    state: present
