---
- name: Install image manipulation software
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - flameshot
    - gimp
    - gimp-plugin-gmic
    - gmic
    - inkscape
    - imagemagick
