---
- import_tasks: fonts.yml

- import_tasks: multimedia.yml

- import_tasks: email.yml
  when: desktop_install_email

- import_tasks: image.yml
  when: desktop_install_image

- import_tasks: messaging.yml
  when: desktop_install_messaging

- import_tasks: extra.yml
  when: desktop_install_extra

- name: Terminal emulators and desktop utilities
  pacman:
    name:
      - alacritty
      - gnome-keyring
      - gpicview-gtk3
      - keepassxc
      - numlockx
      - python-xdg
      - qtkeychain
      - redshift
      - scrot
      - seahorse
      - xdg-user-dirs
    state: present

- name: Thunar and file utilities
  pacman:
    name:
      - ffmpegthumbnailer
      - gvfs
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-smb
      - libgsf
      - nextcloud-client
      - raw-thumbnailer
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - tumbler
      - udiskie
      - udisks2
      - xarchiver
    state: present

- name: Add an ImageMagick PDF thumbnailer
  copy:
    src: imagemagick-pdf.thumbnailer
    dest: /usr/share/thumbnailers/imagemagick-pdf.thumbnailer
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Device configuration utilities
  pacman:
    name:
      - libratbag
      - piper
    state: present
