---
- import_tasks: audio.yml
- import_tasks: fonts.yml
- import_tasks: image.yml
- import_tasks: multimedia.yml
- import_tasks: storage.yml
- import_tasks: video.yml
- import_tasks: applications.yml

