---
- name: Install A/V libraries
  pacman:
    name:
      - ffmpeg
      - gstreamer
    state: present

- name: Install dictionaries
  pacman:
    name:
      - aspell
      - aspell-en
      - aspell-fr
      - hunspell
      - hunspell-fr
      - hunspell-en
    state: present

- name: Install eBook and PDF readers
  pacman:
    name:
      - pdfpc
      - zathura
      - zathura-cb
      - zathura-djvu
      - zathura-pdf-poppler
      - zathura-ps
    state: present

- name: Install Web browsers
  pacman:
    name:
      - chromium
      - firefox
      - flashplugin
    state: present

- name: Install x86 libraries (multilib)
  pacman:
    name:
      - lib32-flashplugin
    state: present
  when: "'multilib' in pacman_repositories"

- name: Install media players
  pacman:
    name:
      - moc
      - mpv
      - smplayer
    state: present
