---
- name: Install A/V libraries
  pacman:
    name:
      - ffmpeg
      - gstreamer
      - guvcview-qt
      - v4l2loopback-dkms
    state: present

- name: Install dictionaries
  pacman:
    name:
      - aspell
      - aspell-en
      - aspell-fr
      - hunspell
      - hunspell-fr
      - hunspell-en_GB
      - hunspell-en_US
    state: present

- name: Install eBook and PDF readers
  pacman:
    name:
      - mupdf
      - mupdf-tools
      - pdfpc
      - zathura
      - zathura-cb
      - zathura-djvu
      - zathura-pdf-mupdf
      - zathura-ps
    state: present

- name: Install Web browsers
  pacman:
    name:
      - chromium
      - firefox
      - geckodriver
    state: present

- name: Install media players
  pacman:
    name:
      - mpd
      - mpv
      - ncmpc
      - ncmpcpp
      - smplayer
      - vlc
    state: present
