---
- name: Install A/V libraries
  pacman:
    name:
      - ffmpeg
      - gstreamer
      - guvcview-qt
      - speech-dispatcher
      - v4l2loopback-dkms
    state: present

- name: Install dictionaries
  pacman:
    name:
      - aspell
      - aspell-en
      - aspell-fr
      - hunspell
      - hunspell-fr
      - hunspell-en_GB
      - hunspell-en_US
    state: present
