---
ansigenome_info:
  synopsis: |
    Installs command-line utilities and management tools for system, filesystem
    and networking tasks.

    To learn more about system and network performance tools, take a look at
    the following articles:

    - `Linux Performance <http://www.brendangregg.com/linuxperf.html>`_
    - `Every Linux networking tool I know <https://wizardzines.com/networking-tools-poster/>`_
    - `Nmap 6 Cookbook <https://nmapcookbook.blogspot.com/2010/02/nmap-cheat-sheet.html>`_
