---
- name: Install CLI utilities
  pacman:
    name:
      - arch-wiki-docs
      - arch-wiki-lite
      - asciinema
      - at
      - bash-completion
      - colordiff
      - dfc
      - dialog
      - diffutils
      - eza
      - fd
      - fzf
      - fzy
      - gnupg
      - inotify-tools
      - jq
      - lynx
      - man-db
      - man-pages
      - multitail
      - neofetch
      - ncdu
      - ncurses
      - parallel
      - p7zip
      - pigz
      - pinentry
      - ranger
      - ripgrep
      - ripgrep-all
      - rsync
      - tmux
      - tmuxp
      - tree
      - unrar
      - unzip
      - xclip
      - yubikey-manager
      - yubikey-personalization
      - zip
      - zoxide
      - zsh
      - zsh-completions
    state: present
