---
- name: "[{{ dotfiles_user_name }}] Install dependencies"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - "{{ dotfiles_user_shell }}"

- name: "[{{ dotfiles_user_name }}] Clone dotfiles repository"
  git:
    repo: "{{ dotfiles_git_repo }}"
    dest: "{{ dotfiles_git_dest }}"
    remote: origin
    version: "{{ dotfiles_git_branch }}"
  become: yes
  become_user: "{{ dotfiles_user_name }}"

- name: "[{{ dotfiles_user_name }}] Create ~/.config"
  file:
    dest: "~{{ dotfiles_user_name }}/.config"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    state: directory
    mode: 0700

- name: "[{{ dotfiles_user_name }}] Deploy symlinks under ~/.config"
  file:
    src: "{{ dotfiles_git_dest }}/config/{{ item.src }}"
    dest: "~{{ dotfiles_user_name }}/.config/{{ item.dest }}"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    state: link
  loop:
    - src: "awesome{{ dotfiles_awesome_version }}"
      dest: awesome
    - src: i3
      dest: i3
    - src: i3status
      dest: i3status
    - src: mpd
      dest: mpd
    - src: ncmpc
      dest: ncmpc
    - src: termite
      dest: termite
    - src: zathura
      dest: zathura

- name: "[{{ dotfiles_user_name }}] Deploy symlinks under ~/"
  file:
    src: "{{ dotfiles_git_dest }}/{{ item.src }}"
    dest: "~{{ dotfiles_user_name }}/{{ item.dest }}"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    state: link
    force: yes
  loop:
    - src: bash/rc.sh
      dest: .bashrc
    - src: bash/aliases.sh
      dest: .bash_aliases
    - src: profile.sh
      dest: .profile
    - src: tmux/tmux.conf
      dest: .tmux.conf
    - src: vim/init.vim
      dest: .vimrc
    - src: Xresources
      dest: .Xresources
    - src: zsh/rc.sh
      dest: .zshrc

- name: "[{{ dotfiles_user_name }}] Deploy Git configuration"
  template:
    src: gitconfig
    dest: "~{{ dotfiles_user_name }}/.gitconfig"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    mode: 0644

- name: "[{{ dotfiles_user_name }}] Deploy Mercurial configuration"
  template:
    src: hgrc
    dest: "~{{ dotfiles_user_name }}/.hgrc"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    mode: 0644
