---
- name: AwesomeWM Desktop
  pacman: name={{ item }} state=present
  with_items:
    - awesome
    - breeze-icons
    - gpicview
    - gvfs
    - gvfs-gphoto2
    - lxappearance
    - oxygen-icons
    - pcmanfm
    - qt5ct
    - redshift
    - rxvt-unicode-terminfo
    - udiskie
    - xarchiver
