---
- name: Text editors
  pacman: name={{ item }} state=present
  with_items:
    - auctex
    - emacs-nox
    - nano
    - poedit

- name: Install development tools
  pacman: name={{ item }} state=present
  with_items:
    - asciidoc
    - boost
    - boost-libs
    - ccache
    - check
    - clang
    - cmake
    - ctags
    - gource
    - extra-cmake-modules
    - doxygen
    - gperf
    - graphviz
    - maven
    - shellcheck
    - texlive-bin
    - texlive-core
    - texlive-fontsextra
    - texlive-latexextra
    - texlive-pictures
    - uncrustify
    - valgrind

- name: Development - Python
  pacman: name={{ item }} state=present
  with_items:
    - hardening-wrapper
    - mpdecimal
    - python-requests
    - python-virtualenv-clone
