---
- name: Install networking utilities
  pacman: name={{ item }} state=present
  with_items:
    - bind-tools
    - curl
    - iperf
    - iperf3
    - net-tools
    - nmap
    - tcpdump
    - whois
    - wget
