---
- name: Install (force) Jack2 audio server
  pacman:
    name: jack2-dbus
    state: present
    force: yes

- name: Install Jack bindings and utilities
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - a2jmidid
    - pulseaudio-jack
    - qjackctl

- name: Install MIDI libraries and software synths
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - fluidsynth
    - qsynth
    - soundfont-fluid
    - timidity++
    - vmpk

- name: Install applications
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ardour
    - jalv
    - libsamplerate
    - lilypond
    - lv2
    - musescore
    - portsmf
    - rubberband
    - supercollider
