---
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
    - python-docker
    - python-docker-pycreds
    - python-dockerpty

- name: Deploy service configuration
  template:
    dest: /etc/systemd/system/docker.service.d/override.conf
    src: docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload systemd daemons and restart docker
