---
- name: Install ALSA and PulseAudio
  pacman:
    name:
      - alsa-plugins
      - alsa-utils
      - pavucontrol
      - pulseaudio
    state: present

- name: Install codecs and tools
  pacman:
    name:
      - cuetools
      - fftw
      - flac
      - libcue
      - libffado
      - libmpcdec
      - mac
      - mp3info
      - opus
      - shntool
      - twolame
      - vorbis-tools
      - wavpack
    state: present
