---
- name: Install packages
  pacman:
    name:
      - docker
      - docker-buildx
      - docker-compose
      - lazydocker
      - python-docker
      - python-docker-pycreds
      - python-dockerpty
    state: present

- name: Create systemd Docker directory
  file:
    name: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy service configuration
  template:
    dest: /etc/systemd/system/docker.service.d/override.conf
    src: docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload systemd daemons and restart docker

- name: Ensure Docker is enabled and started
  systemd:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes
