---
- name: Install (force) Jack2 audio server
  pacman:
    name: jack2-dbus
    state: present
    force: yes

- name: Install Jack bindings, clients and utilities
  pacman:
    name:
      - a2jmidid
      - cadence
      - jack_capture
      - pulseaudio-jack
      - qjackctl
      - rtirq
      - zita-ajbridge
    state: present

- name: Install MIDI libraries and software synths
  pacman:
    name:
      - fluidsynth
      - qsynth
      - rtmidi
      - soundfont-fluid
      - timidity++
      - vmpk
    state: present

- name: Install applications
  pacman:
    name:
      - ardour
      - audacity
      - drumgizmo
      - giada
      - jalv
      - libsamplerate
      - lilypond
      - lv2
      - musescore
      - portsmf
      - rubberband
      - supercollider
    state: present
