---
- name: Install (force) Jack2 audio server
  pacman:
    name: jack2-dbus
    state: present
    force: yes

- name: Install Jack bindings and utilities
  pacman:
    name:
      - a2jmidid
      - pulseaudio-jack
      - qjackctl
    state: present

- name: Install MIDI libraries and software synths
  pacman:
    name:
      - fluidsynth
      - qsynth
      - soundfont-fluid
      - timidity++
      - vmpk
    state: present

- name: Install applications
  pacman:
    name:
      - ardour
      - jalv
      - libsamplerate
      - lilypond
      - lv2
      - musescore
      - portsmf
      - rubberband
      - supercollider
    state: present
