---
- name: Install Jack bindings, clients and utilities
  pacman:
    name:
      - a2jmidid
      - cadence
      - jack2
      - jack_capture
      - pulseaudio-jack
      - qjackctl
      - realtime-privileges
      - rt-tests
      - rtirq
      - schedtool
      - tuna
      - zita-ajbridge
      - zita-convolver
    state: present

- name: Install MIDI libraries and software synths
  pacman:
    name:
      - fluidsynth
      - qmidiarp
      - qsynth
      - rtmidi
      - soundfont-fluid
      - timidity++
      - vmpk
    state: present

- name: Install applications
  pacman:
    name:
      - ardour
      - audacity
      - drumgizmo
      - giada
      - jalv
      - libsamplerate
      - lilypond
      - lv2
      - musescore
      - portsmf
      - rubberband
      - supercollider
    state: present
