---
- include: multimedia.yml

- include: email.yml
  when: desktop_install_email

- include: image.yml
  when: desktop_install_image

- include: messaging.yml
  when: desktop_install_messaging

- include: extra.yml
  when: desktop_install_extra

- name: Terminal emulators and desktop utilities
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - gpicview
    - libgnome-keyring
    - numlockx
    - python-xdg
    - qtkeychain
    - redshift
    - rxvt-unicode
    - rxvt-unicode-terminfo
    - scrot
    - termite
    - termite-terminfo

- name: PCManFM and file utilities
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ffmpegthumbnailer
    - gvfs
    - gvfs-gphoto2
    - imagemagick
    - libgsf
    - pcmanfm
    - xarchiver
    - udiskie

- name: Add an ImageMagick PDF thumbnailer
  copy:
    src: imagemagick-pdf.thumbnailer
    dest: /usr/share/thumbnailers/imagemagick-pdf.thumbnailer
    owner: root
    group: root
    mode: 0644
    backup: yes
