---
- name: AwesomeWM Desktop and graphical toolkits
  pacman:
    name:
      - arc-gtk-theme
      - breeze-icons
      - dmenu
      - feh
      - fltk
      - gtk-engine-murrine
      - i3-wm
      - i3lock
      - i3status
      - lxappearance
      - numix-gtk-theme
      - qt5-styleplugins
      - qt5ct
      - tk
    state: present
