---
- name: Install LibreOffice
  pacman:
    name: "libreoffice-{{ libreoffice_version }}"
    state: present

- name: Install LibreOffice localizations
  pacman:
    name: "{{ libreoffice_languages }}"
    state: present
