---
- name: Create /etc/X11/xorg.conf.d
  file:
    name: /etc/X11/xorg.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy libinput configuration
  template:
    src: "etc/X11/xorg.conf.d/{{ item }}"
    dest: "/etc/X11/xorg.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop:
    - 20-libinput.conf
    - 40-keyboard.conf
