---
ansigenome_info:
  synopsis: |
    Installs Linux audio libraries and codecs:

    - `ALSA <http://www.alsa-project.org/main/index.php/Main_Page>`_
    - `Pulseaudio <https://www.freedesktop.org/wiki/Software/PulseAudio/>`_
