---
- name: Install LightDM
  pacman:
    name:
      - accountsservice
      - lightdm
      - lightdm-gtk-greeter
      - lightdm-gtk-greeter-settings
      - light-locker
    state: present

- name: Define user accounts hidden from LightDM
  lineinfile:
    dest: /etc/lightdm/users.conf
    line: 'hidden-users=nobody nobody4 noaccess {{ ansible_user }}'
    regexp: '^hidden-users'

- name: Ensure LightDM is enabled and started
  systemd:
    name: lightdm
    enabled: yes
    state: started
