---
- name: Install LightDM
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - accountsservice
    - lightdm
    - lightdm-gtk-greeter
    - light-locker

- name: Define user accounts hidden from LightDM
  lineinfile:
    dest: /etc/lightdm/users.conf
    line: 'hidden-users=nobody nobody4 noaccess {{ ansible_user }}'
    regexp: '^hidden-users'

- name: Ensure LightDM is enabled and started
  systemd:
    name: lightdm
    enabled: yes
    state: started
