---
- name: Install command-line utilities
  apt:
    name:
      - bash
      - bash-completion
      - dialog
      - gnupg
      - jq
      - lynx
      - multitail
      - ncurses-term
      - p7zip-full
      - p7zip-rar
      - pigz
      - ranger
      - rsync
      - silversearcher-ag
      - tmux
      - tmuxp
      - tree
      - unrar
      - unzip
      - xclip
      - zip
      - zsh
    state: present
