---
- name: Development - Python
  apt:
    name:
      - libmpdec2
      - libmpdec-dev
      - python-dev
      - python-pip
      - python-virtualenv
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - virtualenv
    state: present
