---
- name: Add the GPG key for NodeSource repositories
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: "Add NodeSource {{ nodejs_major_version }} repository"
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x {{ ansible_distribution_release }} main'
    update_cache: yes

- name: Install Node.js
  apt:
    name: "nodejs={{ nodejs_major_version }}.*"
    state: present

- name: Set NODE_PATH under /etc/environment
  lineinfile:
    dest: /etc/environment
    regexp: '^NODE_PATH'
    line: 'NODE_PATH="/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/local/lib/npm/lib/node_modules"'

- name: Install Bower, Gulp and Yarn globally
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop:
    - bower
    - gulp
    - npx
    - yarn
