---
# Official repositories to enable:
# - testing
# - core
# - extra
# - community-testing
# - community
# - multilib-testing
# - multilib
#
# See https://wiki.archlinux.org/index.php/Official_repositories
pacman_repositories:
  - core
  - extra
  - community
