---
# Official repositories to enable:
# - core
# - core-testing
# - extra
# - extra-testing
# - multilib
# - multilib-testing
#
# See https://wiki.archlinux.org/index.php/Official_repositories
pacman_repositories:
  - core
  - extra
  - multilib

# Whether to enable parallel downloads
pacman_parallel_downloads: 5
