---
- name: Refresh package cache
  pacman: update_cache=yes

# Core
- include: packages/cli.yml
- include: packages/dev.yml
- include: packages/networking.yml
- include: packages/system.yml

# Desktop
- include: packages/audio.yml
- include: packages/desktop.yml

# Extras
- include: packages/games.yml
  when: "{{ arch_games }} == True"

- include: packages/lulz.yml
  when: "{{ arch_lulz }} == True"
