---
- name: Setup base system
  hosts: archlinux
  roles:
    - role: vt.archlinux/pacman
      tags: ['pacman']

    - role: vt.archlinux/base
      tags: ['base']

    - role: vt.archlinux/x11
      tags: ['x11']

    # - role: vt.common/x11-config
    #   tags: ['x11']

    - role: vt.common/network-time
      tags: ['ntp']

    - role: vt.common/locales
      tags: ['locales']

    - role: vt.archlinux/sddm
      tags: ['desktop-manager', 'sddm', 'wayland']

    - role: vt.archlinux/hyprland-wm
      tags: ['desktop', 'hyprland', 'wayland']

    - role: vt.archlinux/desktop
      tags: ['desktop', 'office']

    - role: vt.archlinux/docker
      tags: ['container', 'docker']


- name: Setup NVIDIA graphics
  hosts: archlinux-nvidia
  roles:
    - role: vt.archlinux/nvidia
      tags: ['docker', 'gpu', 'nvidia']
