---
- name: Setup base system
  hosts: archlinux
  roles:
    - role: vt.archlinux/pacman
      tags: ['pacman']

    - role: vt.archlinux/base
      tags: ['base']

    - role: vt.archlinux/x11
      tags: ['x11']

    # - role: vt.common/x11-config
    #   tags: ['x11']

    - role: vt.common/network-time
      tags: ['ntp']

    - role: vt.common/locales
      tags: ['locales']

    - role: vt.archlinux/lightdm
      tags: ['lightdm']

    - role: vt.archlinux/i3-wm
      tags: ['desktop', 'i3']

    - role: vt.archlinux/desktop
      tags: ['desktop', 'office']

    - role: vt.archlinux/audio-desktop
      tags: ['audio']
