---
- name: Clone repository
  git:
    repo: "{{ dotfiles_git_repo }}"
    dest: "{{ dotfiles_git_dest }}"
  become_user: "{{ dotfiles_user_name }}"

- name: Deploy configuration symlinks under ~/.config
  file:
    src: "{{ dotfiles_git_dest }}/config/{{ item.src }}"
    dest: "~{{ dotfiles_user_name }}/.config/{{ item.dest }}"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    state: link
  with_items:
    - src: "awesome{{ dotfiles_awesome_version }}"
      dest: awesome
    - src: termite
      dest: termite
    - src: zathura
      dest: zathura

- name: Deploy configuration symlinks under ~/
  file:
    src: "{{ dotfiles_git_dest }}/{{ item.src }}"
    dest: "~{{ dotfiles_user_name }}/{{ item.dest }}"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    state: link
  with_items:
    - src: bash/rc.sh
      dest: .bashrc
    - src: bash/aliases.sh
      dest: .bash_aliases
    - src: tmux/tmux.conf
      dest: .tmux.conf
    - src: Xresources
      dest: .Xresources
    - src: zsh/rc.sh
      dest: .zshrc

- name: Deploy initial Emacs configuration
  template:
    src: emacs.el
    dest: "~{{ dotfiles_user_name }}/.emacs"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    force: no
    mode: 0644

- name: Deploy Git configuration
  template:
    src: gitconfig
    dest: "~{{ dotfiles_user_name }}/.gitconfig"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    mode: 0644

- name: Deploy Mercurial configuration
  template:
    src: hgrc
    dest: "~{{ dotfiles_user_name }}/.hgrc"
    owner: "{{ dotfiles_user_name }}"
    group: "{{ dotfiles_user_group }}"
    mode: 0644
