---
- name: Create /etc/pacman.conf.d/
  file:
    name: /etc/pacman.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Deploy README for additional repositories
  copy:
    src: readme.txt
    dest: /etc/pacman.conf.d/readme.txt
    owner: root
    group: root
    mode: 0644

- name: Deploy Pacman configuration
  template:
    src: pacman.conf
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - refresh pacman cache

- meta: flush_handlers
